#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : audacious-plugins
Version  : 3.10.1
Release  : 2
URL      : https://distfiles.audacious-media-player.org/audacious-plugins-3.10.1.tar.bz2
Source0  : https://distfiles.audacious-media-player.org/audacious-plugins-3.10.1.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 MIT
Requires: audacious-plugins-data = %{version}-%{release}
Requires: audacious-plugins-lib = %{version}-%{release}
Requires: audacious-plugins-license = %{version}-%{release}
Requires: audacious-plugins-locales = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : curl-dev
BuildRequires : glib-dev
BuildRequires : gtk+-dev
BuildRequires : libnotify-dev
BuildRequires : libogg-dev
BuildRequires : libsamplerate-dev
BuildRequires : libsndfile-dev
BuildRequires : mpg123-dev
BuildRequires : pkgconfig(Qt5OpenGL)
BuildRequires : pkgconfig(audacious)
BuildRequires : pkgconfig(flac)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(sdl)
BuildRequires : pkgconfig(sdl2)
BuildRequires : pkgconfig(vorbis)
BuildRequires : wavpack-dev

%description
psf2 plugin
-----------
What is this?
It's a PSF2 plugin based on:
* UPSE
* Audio Overload
* Highly Experimental

%package data
Summary: data components for the audacious-plugins package.
Group: Data

%description data
data components for the audacious-plugins package.


%package lib
Summary: lib components for the audacious-plugins package.
Group: Libraries
Requires: audacious-plugins-data = %{version}-%{release}
Requires: audacious-plugins-license = %{version}-%{release}

%description lib
lib components for the audacious-plugins package.


%package license
Summary: license components for the audacious-plugins package.
Group: Default

%description license
license components for the audacious-plugins package.


%package locales
Summary: locales components for the audacious-plugins package.
Group: Default

%description locales
locales components for the audacious-plugins package.


%prep
%setup -q -n audacious-plugins-3.10.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568143794
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static --disable-neon \
--with-ffmpeg=none
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1568143794
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/audacious-plugins
cp COPYING %{buildroot}/usr/share/package-licenses/audacious-plugins/COPYING
cp src/aosd/ghosd-license %{buildroot}/usr/share/package-licenses/audacious-plugins/src_aosd_ghosd-license
cp src/psf/peops/License.txt %{buildroot}/usr/share/package-licenses/audacious-plugins/src_psf_peops_License.txt
cp src/psf/peops2/License.txt %{buildroot}/usr/share/package-licenses/audacious-plugins/src_psf_peops2_License.txt
cp src/xsf/desmume/COPYING %{buildroot}/usr/share/package-licenses/audacious-plugins/src_xsf_desmume_COPYING
%make_install
%find_lang audacious-plugins

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/audacious/Skins/Classic/balance.png
/usr/share/audacious/Skins/Classic/cbuttons.png
/usr/share/audacious/Skins/Classic/eq_ex.png
/usr/share/audacious/Skins/Classic/eqmain.png
/usr/share/audacious/Skins/Classic/main.png
/usr/share/audacious/Skins/Classic/monoster.png
/usr/share/audacious/Skins/Classic/nums_ex.png
/usr/share/audacious/Skins/Classic/playpaus.png
/usr/share/audacious/Skins/Classic/pledit.png
/usr/share/audacious/Skins/Classic/pledit.txt
/usr/share/audacious/Skins/Classic/posbar.png
/usr/share/audacious/Skins/Classic/shufrep.png
/usr/share/audacious/Skins/Classic/skin-classic.hints
/usr/share/audacious/Skins/Classic/skin.hints
/usr/share/audacious/Skins/Classic/text.png
/usr/share/audacious/Skins/Classic/titlebar.png
/usr/share/audacious/Skins/Classic/viscolor.txt
/usr/share/audacious/Skins/Classic/volume.png
/usr/share/audacious/Skins/Classic1.3/balance.png
/usr/share/audacious/Skins/Classic1.3/cbuttons.png
/usr/share/audacious/Skins/Classic1.3/eq_ex.png
/usr/share/audacious/Skins/Classic1.3/eqmain.png
/usr/share/audacious/Skins/Classic1.3/main.png
/usr/share/audacious/Skins/Classic1.3/monoster.png
/usr/share/audacious/Skins/Classic1.3/nums_ex.png
/usr/share/audacious/Skins/Classic1.3/playpaus.png
/usr/share/audacious/Skins/Classic1.3/pledit.png
/usr/share/audacious/Skins/Classic1.3/pledit.txt
/usr/share/audacious/Skins/Classic1.3/posbar.png
/usr/share/audacious/Skins/Classic1.3/shufrep.png
/usr/share/audacious/Skins/Classic1.3/skin-classic.hints
/usr/share/audacious/Skins/Classic1.3/skin.hints
/usr/share/audacious/Skins/Classic1.3/text.png
/usr/share/audacious/Skins/Classic1.3/titlebar.png
/usr/share/audacious/Skins/Classic1.3/viscolor.txt
/usr/share/audacious/Skins/Classic1.3/volume.png
/usr/share/audacious/Skins/Default/cbuttons.png
/usr/share/audacious/Skins/Default/eq_ex.png
/usr/share/audacious/Skins/Default/eqmain.png
/usr/share/audacious/Skins/Default/main.png
/usr/share/audacious/Skins/Default/monoster.png
/usr/share/audacious/Skins/Default/nums_ex.png
/usr/share/audacious/Skins/Default/playpaus.png
/usr/share/audacious/Skins/Default/pledit.png
/usr/share/audacious/Skins/Default/pledit.txt
/usr/share/audacious/Skins/Default/posbar.png
/usr/share/audacious/Skins/Default/shufrep.png
/usr/share/audacious/Skins/Default/skin.hints
/usr/share/audacious/Skins/Default/text.png
/usr/share/audacious/Skins/Default/titlebar.png
/usr/share/audacious/Skins/Default/viscolor.txt
/usr/share/audacious/Skins/Default/volume.png
/usr/share/audacious/Skins/Ivory/balance.png
/usr/share/audacious/Skins/Ivory/cbuttons.png
/usr/share/audacious/Skins/Ivory/eq_ex.png
/usr/share/audacious/Skins/Ivory/eqmain.png
/usr/share/audacious/Skins/Ivory/main.png
/usr/share/audacious/Skins/Ivory/monoster.png
/usr/share/audacious/Skins/Ivory/nums_ex.png
/usr/share/audacious/Skins/Ivory/playpaus.png
/usr/share/audacious/Skins/Ivory/pledit.png
/usr/share/audacious/Skins/Ivory/pledit.txt
/usr/share/audacious/Skins/Ivory/posbar.png
/usr/share/audacious/Skins/Ivory/shufrep.png
/usr/share/audacious/Skins/Ivory/skin.hints
/usr/share/audacious/Skins/Ivory/text.png
/usr/share/audacious/Skins/Ivory/titlebar.png
/usr/share/audacious/Skins/Ivory/viscolor.txt
/usr/share/audacious/Skins/Ivory/volume.png
/usr/share/audacious/Skins/Osmosis/balance.png
/usr/share/audacious/Skins/Osmosis/cbuttons.png
/usr/share/audacious/Skins/Osmosis/eq_ex.png
/usr/share/audacious/Skins/Osmosis/eqmain.png
/usr/share/audacious/Skins/Osmosis/main.png
/usr/share/audacious/Skins/Osmosis/monoster.png
/usr/share/audacious/Skins/Osmosis/nums_ex.png
/usr/share/audacious/Skins/Osmosis/playpaus.png
/usr/share/audacious/Skins/Osmosis/pledit.png
/usr/share/audacious/Skins/Osmosis/pledit.txt
/usr/share/audacious/Skins/Osmosis/posbar.png
/usr/share/audacious/Skins/Osmosis/shufrep.png
/usr/share/audacious/Skins/Osmosis/skin.hints
/usr/share/audacious/Skins/Osmosis/text.png
/usr/share/audacious/Skins/Osmosis/titlebar.png
/usr/share/audacious/Skins/Osmosis/viscolor.txt
/usr/share/audacious/Skins/Osmosis/volume.png
/usr/share/audacious/Skins/Refugee/cbuttons.png
/usr/share/audacious/Skins/Refugee/eq_ex.png
/usr/share/audacious/Skins/Refugee/eqmain.png
/usr/share/audacious/Skins/Refugee/main.png
/usr/share/audacious/Skins/Refugee/monoster.png
/usr/share/audacious/Skins/Refugee/nums_ex.png
/usr/share/audacious/Skins/Refugee/playpaus.png
/usr/share/audacious/Skins/Refugee/pledit.png
/usr/share/audacious/Skins/Refugee/pledit.txt
/usr/share/audacious/Skins/Refugee/posbar.png
/usr/share/audacious/Skins/Refugee/shufrep.png
/usr/share/audacious/Skins/Refugee/skin.hints
/usr/share/audacious/Skins/Refugee/text.png
/usr/share/audacious/Skins/Refugee/titlebar.png
/usr/share/audacious/Skins/Refugee/viscolor.txt
/usr/share/audacious/Skins/Refugee/volume.png
/usr/share/audacious/Skins/TinyPlayer/balance.png
/usr/share/audacious/Skins/TinyPlayer/cbuttons.png
/usr/share/audacious/Skins/TinyPlayer/eq_ex.png
/usr/share/audacious/Skins/TinyPlayer/eqmain.png
/usr/share/audacious/Skins/TinyPlayer/main.png
/usr/share/audacious/Skins/TinyPlayer/monoster.png
/usr/share/audacious/Skins/TinyPlayer/nums_ex.png
/usr/share/audacious/Skins/TinyPlayer/playpaus.png
/usr/share/audacious/Skins/TinyPlayer/pledit.png
/usr/share/audacious/Skins/TinyPlayer/pledit.txt
/usr/share/audacious/Skins/TinyPlayer/posbar.png
/usr/share/audacious/Skins/TinyPlayer/shufrep.png
/usr/share/audacious/Skins/TinyPlayer/skin.hints
/usr/share/audacious/Skins/TinyPlayer/text.png
/usr/share/audacious/Skins/TinyPlayer/titlebar.png
/usr/share/audacious/Skins/TinyPlayer/viscolor.txt
/usr/share/audacious/Skins/TinyPlayer/volume.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/audacious/Container/asx.so
/usr/lib64/audacious/Container/asx3.so
/usr/lib64/audacious/Container/audpl.so
/usr/lib64/audacious/Container/m3u.so
/usr/lib64/audacious/Container/pls.so
/usr/lib64/audacious/Container/xspf.so
/usr/lib64/audacious/Effect/compressor.so
/usr/lib64/audacious/Effect/crossfade.so
/usr/lib64/audacious/Effect/crystalizer.so
/usr/lib64/audacious/Effect/echo.so
/usr/lib64/audacious/Effect/ladspa.so
/usr/lib64/audacious/Effect/mixer.so
/usr/lib64/audacious/Effect/resample.so
/usr/lib64/audacious/Effect/silence-removal.so
/usr/lib64/audacious/Effect/speed-pitch.so
/usr/lib64/audacious/Effect/stereo.so
/usr/lib64/audacious/Effect/voice_removal.so
/usr/lib64/audacious/General/alarm.so
/usr/lib64/audacious/General/albumart.so
/usr/lib64/audacious/General/aosd.so
/usr/lib64/audacious/General/delete-files.so
/usr/lib64/audacious/General/gtkui.so
/usr/lib64/audacious/General/hotkey.so
/usr/lib64/audacious/General/lyricwiki.so
/usr/lib64/audacious/General/mpris2.so
/usr/lib64/audacious/General/notify.so
/usr/lib64/audacious/General/playlist-manager.so
/usr/lib64/audacious/General/scrobbler.so
/usr/lib64/audacious/General/search-tool.so
/usr/lib64/audacious/General/skins.so
/usr/lib64/audacious/General/song_change.so
/usr/lib64/audacious/General/statusicon.so
/usr/lib64/audacious/Input/console.so
/usr/lib64/audacious/Input/flacng.so
/usr/lib64/audacious/Input/madplug.so
/usr/lib64/audacious/Input/metronom.so
/usr/lib64/audacious/Input/psf2.so
/usr/lib64/audacious/Input/sndfile.so
/usr/lib64/audacious/Input/tonegen.so
/usr/lib64/audacious/Input/vorbis.so
/usr/lib64/audacious/Input/vtx.so
/usr/lib64/audacious/Input/wavpack.so
/usr/lib64/audacious/Input/xsf.so
/usr/lib64/audacious/Output/alsa.so
/usr/lib64/audacious/Output/filewriter.so
/usr/lib64/audacious/Output/oss4.so
/usr/lib64/audacious/Output/pulse_audio.so
/usr/lib64/audacious/Output/sdlout.so
/usr/lib64/audacious/Transport/gio.so
/usr/lib64/audacious/Visualization/blur_scope.so
/usr/lib64/audacious/Visualization/cairo-spectrum.so
/usr/lib64/audacious/Visualization/gl-spectrum.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/audacious-plugins/COPYING
/usr/share/package-licenses/audacious-plugins/src_aosd_ghosd-license
/usr/share/package-licenses/audacious-plugins/src_psf_peops2_License.txt
/usr/share/package-licenses/audacious-plugins/src_psf_peops_License.txt
/usr/share/package-licenses/audacious-plugins/src_xsf_desmume_COPYING

%files locales -f audacious-plugins.lang
%defattr(-,root,root,-)

